RecipeFormatVersion: 2020-01-25
ComponentName: aws.greengrass.labs.SecretsManagerClient
ComponentVersion: 1.0.0
ComponentDescription: A component providing a client to fetch secrets from
  SecretsManager. Use by calling java -jar
  {aws.greengrass.labs.SecrectsManagerClient:artifacts:path}/secrects.jar
  <secretId>
ComponentPublisher: Amazon Web Services
ComponentDependencies:
  aws.greengrass.SecretManager:
    VersionRequirement: ">0.0.0"
    DependencyType: SOFT
Manifests:
  - Platform:
      os: /linux/
      architecture: /x86|aarch64|amd64|arm/
    Artifacts:
      - URI: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/secrets.jar
        Permission:
          Execute: ALL
          Read: ALL
